/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DataBase;


import ApplicationGestionVmt.BDD;
import ApplicationGestionVmt.Parametres;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;


/**
 *
 * @author jilalhassanjilal
 */
public class Logine extends javax.swing.JFrame {
     
    ResultSet rs;
    BDD db;
    String username1, password1, hak;
    JOptionPane job, job1;
    /**
     * Creates new form Logine
     */
    public Logine() {
        db = new BDD(new Parametres().HOST_DB, new Parametres().USERNAME_DB,new Parametres().PASSWORD_DB, new Parametres().IPHOST, new Parametres().PORT); 
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_logine = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        error = new javax.swing.JLabel();
        txt_passe = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();

        jLabel5.setForeground(new java.awt.Color(242, 9, 9));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DataBase/images/photo.jpg"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(4, 243, 243));
        jLabel1.setText("Connection");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(140, 60, 125, 31);

        jLabel2.setFont(new java.awt.Font("Ubuntu Light", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(9, 190, 250));
        jLabel2.setText("Password :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(60, 170, 110, 21);

        jLabel3.setFont(new java.awt.Font("Ubuntu Light", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(6, 201, 250));
        jLabel3.setText("Logine :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(70, 120, 70, 21);

        txt_logine.setFont(new java.awt.Font("TakaoPGothic", 0, 14)); // NOI18N
        getContentPane().add(txt_logine);
        txt_logine.setBounds(190, 120, 170, 30);

        jButton1.setFont(new java.awt.Font("Ubuntu Light", 3, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(46, 26, 182));
        jButton1.setText("Log-in");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(40, 240, 140, 40);

        jButton2.setFont(new java.awt.Font("Ubuntu Light", 3, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(46, 26, 182));
        jButton2.setText("Quit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(230, 240, 140, 40);
        getContentPane().add(error);
        error.setBounds(170, 210, 160, 0);
        getContentPane().add(txt_passe);
        txt_passe.setBounds(190, 160, 170, 30);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DataBase/images/photo.jpg"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 0, 440, 290);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        job1= new JOptionPane();
        int option = job1.showConfirmDialog(null, "are you sure to quit the connection interface?", "skipping connectionn", 
                JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
                if(option == JOptionPane.OK_OPTION)dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        rs = db.querySelectAll("users", "logine='" + txt_logine.getText() + "' and password='" + txt_passe.getText() + "'");
        try {
            while (rs.next()) {
                username1 = rs.getString("logine");
                password1 = rs.getString("password");
                hak = rs.getString("type");
            }
        } catch (SQLException ex) {
            Logger.getLogger(Logine.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        if (username1 == null && password1 == null) {
            
                
          job=new JOptionPane();
          job.showMessageDialog(null, "password or logine incorrect", "Error",JOptionPane.ERROR_MESSAGE);
            jLabel5.setText("incorrect password or logine");
            jLabel5.setVisible(true);
            
        }
        
        else {
            if (hak.equals("admin")) {
                principal h = new principal();
                h.setVisible(true);
                this.dispose();
            } else {
                VMT k = new VMT();
                k.setVisible(true);
                this.dispose();
            }
        }
        
        
                                            
    }//GEN-LAST:event_jButton1ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Logine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Logine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Logine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Logine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Logine().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel error;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txt_logine;
    private javax.swing.JPasswordField txt_passe;
    // End of variables declaration//GEN-END:variables
}
