/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DataBase;


import ApplicationGestionVmt.BDD;
import ApplicationGestionVmt.Parametres;
import ApplicationGestionVmt.ResultSetTableModel;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author jilalhassanjilal
 */
public class panne extends javax.swing.JFrame {

   ResultSet rs;
   BDD db;
    public panne() {
        db = new BDD(new Parametres().HOST_DB, new Parametres().USERNAME_DB, new Parametres().PASSWORD_DB, 
           new Parametres().IPHOST, new Parametres().PORT);
        initComponents();
    }
    public void table(){
        String a[]={"id_panne", "info_panne","date_panne","status_panne"};
        rs=db.querySelect(a, "panne");
        table_panne.setModel(new ResultSetTableModel(rs));
    }
    public void actualiser(){
        txt_info.setText("");
        txt_date.setText("");
        com_sta.setSelectedItem("status_panne");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_panne = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_date = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        com_sta = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        com_rec = new javax.swing.JComboBox<>();
        jButton5 = new javax.swing.JButton();
        txt_rec = new javax.swing.JTextField();
        txt_info = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DataBase/images/photo.jpg"))); // NOI18N

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DataBase/images/photo.jpg"))); // NOI18N
        jLabel7.setText("jLabel7");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(11, 212, 243));
        jLabel1.setText("gestion de panne");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(230, 10, 130, 40);

        table_panne.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "id_panne", "info_panne", "date_panne", "status_panne"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table_panne.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_panneMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_panne);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(50, 50, 510, 70);

        jButton1.setBackground(new java.awt.Color(184, 218, 241));
        jButton1.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jButton1.setForeground(new java.awt.Color(83, 11, 117));
        jButton1.setText("Actualiser");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(410, 130, 90, 50);

        jButton2.setBackground(new java.awt.Color(184, 218, 241));
        jButton2.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jButton2.setForeground(new java.awt.Color(83, 11, 117));
        jButton2.setText("Ajouter");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(120, 130, 80, 50);

        jButton3.setBackground(new java.awt.Color(184, 218, 241));
        jButton3.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jButton3.setForeground(new java.awt.Color(83, 11, 117));
        jButton3.setText("Supprimer");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(210, 130, 90, 50);

        jButton4.setBackground(new java.awt.Color(184, 218, 241));
        jButton4.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jButton4.setForeground(new java.awt.Color(83, 11, 117));
        jButton4.setText("Modifier");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(310, 130, 90, 50);

        jLabel2.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(11, 212, 243));
        jLabel2.setText("Inforamtion panne:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 290, 150, 20);

        jLabel3.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(11, 212, 243));
        jLabel3.setText("Date panne :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 330, 90, 30);

        txt_date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_dateActionPerformed(evt);
            }
        });
        getContentPane().add(txt_date);
        txt_date.setBounds(150, 330, 210, 30);

        jLabel4.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(11, 212, 243));
        jLabel4.setText("status de la panne:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 370, 140, 20);

        com_sta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "status_panne", "reparée", "non_reparée" }));
        getContentPane().add(com_sta);
        com_sta.setBounds(150, 370, 210, 20);

        jLabel5.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(11, 212, 243));
        jLabel5.setText("rechercher par categories:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(400, 270, 189, 20);

        com_rec.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "id_panne", "info_panne", "date_panne", "status_panne" }));
        getContentPane().add(com_rec);
        com_rec.setBounds(600, 270, 91, 20);

        jButton5.setBackground(new java.awt.Color(184, 218, 241));
        jButton5.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jButton5.setForeground(new java.awt.Color(83, 11, 117));
        jButton5.setText("rechercher");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(460, 310, 110, 50);
        getContentPane().add(txt_rec);
        txt_rec.setBounds(580, 320, 120, 20);
        getContentPane().add(txt_info);
        txt_info.setBounds(150, 290, 210, 20);

        jLabel8.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(6, 200, 248));
        jLabel8.setText("formulaire d'ajout");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(100, 230, 160, 30);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DataBase/images/photo.jpg"))); // NOI18N
        jLabel9.setText("jLabel9");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(0, 0, 790, 450);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_dateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_dateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_dateActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
 if(txt_info.getText().equals("")||txt_date.getText().equals("")||com_sta.getSelectedItem().equals("status_panne")){
     JOptionPane.showConfirmDialog(null,"the informations they are not complet","Caution",JOptionPane.OK_OPTION,JOptionPane.INFORMATION_MESSAGE);
 }else{
     String[] con ={"info_panne","date_panne","status_panne"};
     String[] info={txt_info.getText(),txt_date.getText(),com_sta.getSelectedItem().toString()};
     System.out.println(db.queryInsert("panne", con, info));
     table();
     actualiser();
     
 }
 
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
actualiser(); table();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
String id=String.valueOf(table_panne.getValueAt(table_panne.getSelectedRow(),0));
if(JOptionPane.showConfirmDialog(null,"you must make sure that you want to delete this panne","Warning",JOptionPane.OK_OPTION,JOptionPane.WARNING_MESSAGE)==JOptionPane.OK_OPTION){
System.out.println(db.queryDelete("panne", "id_panne="+id));
}else{
return;
 }
table();// TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
if(txt_info.getText().equals("")||txt_date.getText().equals("")||com_sta.getSelectedItem().equals("status_panne")){
JOptionPane.showConfirmDialog(null,"you must complet the information","information",JOptionPane.OK_OPTION,JOptionPane.INFORMATION_MESSAGE);

}else{
String con[]={"info_panne","date_panne","status_panne"};
String info[]={txt_info.getText(),txt_date.getText(),com_sta.getSelectedItem().toString()};
String id=String.valueOf(table_panne.getValueAt(table_panne.getSelectedRow(),0));
System.out.println(db.queryUpdate("panne", con, info, "id_panne="+id));
table();
actualiser();
}    // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void table_panneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_panneMouseClicked
txt_info.setText(String.valueOf(table_panne.getValueAt(table_panne.getSelectedRow(),1)));
txt_date.setText(String.valueOf(table_panne.getValueAt(table_panne.getSelectedRow(),2)));
com_sta.setSelectedItem(String.valueOf(table_panne.getValueAt(table_panne.getSelectedRow(),3)));// TODO add your handling code here:
    }//GEN-LAST:event_table_panneMouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
if(txt_rec.getText().equals("")){
 JOptionPane.showConfirmDialog(null,"please enter anything to search","information",JOptionPane.OK_OPTION,JOptionPane.INFORMATION_MESSAGE);
 
}else{
    if(com_rec.getSelectedItem().equals("id_panne")){
      rs=db.querySelectAll("panne", "id_panne LIKE'%"+txt_rec.getText()+"%'");
      table_panne.setModel(new ResultSetTableModel(rs));
    }else if(com_rec.getSelectedItem().equals("info_panne")){
        rs=db.querySelectAll("panne", "info_panne LIKE '%"+txt_rec.getText()+"%'");
        table_panne.setModel(new ResultSetTableModel(rs));
    }else if(com_rec.getSelectedItem().equals("date_panne")){
        rs=db.querySelectAll("panne", "date_panne LIKE '%"+txt_rec.getText()+"%'");
        table_panne.setModel(new ResultSetTableModel(rs));
    }else if(com_rec.getSelectedItem().equals("status_panne")){
        rs=db.querySelectAll("panne", "status_panne LIKE '%"+txt_rec.getText()+"%'");
        table_panne.setModel(new ResultSetTableModel(rs));
    }
}// TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(panne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(panne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(panne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(panne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new panne().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> com_rec;
    private javax.swing.JComboBox<String> com_sta;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table_panne;
    private javax.swing.JTextField txt_date;
    private javax.swing.JTextField txt_info;
    private javax.swing.JTextField txt_rec;
    // End of variables declaration//GEN-END:variables
}
