/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DataBase;


import ApplicationGestionVmt.BDD;
import ApplicationGestionVmt.Parametres;
import ApplicationGestionVmt.ResultSetTableModel;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author jilalhassanjilal
 */
public class utilisateur extends javax.swing.JFrame {

    ResultSet rs;
    JOptionPane jo, jo1;
    BDD db;
    public utilisateur() {
        db = new BDD(new Parametres().HOST_DB, new Parametres().USERNAME_DB, new Parametres().PASSWORD_DB, 
                new Parametres().IPHOST, new Parametres().PORT);
        initComponents();
    } 
    //methode permettant de visualiser les informatino contenu dans la base dans le tableau
     public void table() {
        String a[] = {"id","logine", "password", "type", "nom", "prenom", "telephone", "email"};
        rs = db.querySelect(a, "users");
        table_user.setModel(new ResultSetTableModel(rs));
    }
     //cette methode elle permet d'actualiser la liste
     void actualiser() {
        id_us.setText("");
        txt_log.setText("");
        txt_pas.setText("");
        txt_nom.setText("");
        txt_prenom.setText("");
        txt_tel.setText("");
        txt_email.setText("");
        txt_typ.setSelectedItem("Typpppppe");
     }
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_user = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txt_tel = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        id_us = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_log = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_typ = new javax.swing.JComboBox<>();
        txtrech = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        comrech = new javax.swing.JComboBox<>();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txt_pas = new javax.swing.JTextField();
        txt_nom = new javax.swing.JTextField();
        txt_prenom = new javax.swing.JTextField();
        txt_email = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Garuda", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(7, 193, 252));
        jLabel1.setText("user interface");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(192, 12, 192, 40);

        jScrollPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane1MouseClicked(evt);
            }
        });

        table_user.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "id", "id_user", "username", "password", "type_users", "nom", "prenom", "telephone", "email"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table_user.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_userMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_user);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(0, 60, 760, 80);

        jButton1.setBackground(new java.awt.Color(194, 217, 218));
        jButton1.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(27, 137, 136));
        jButton1.setText("Ajouter");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(100, 190, 100, 50);

        jButton2.setBackground(new java.awt.Color(194, 217, 218));
        jButton2.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(27, 137, 136));
        jButton2.setText("Delette");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(200, 190, 110, 50);

        jButton3.setBackground(new java.awt.Color(194, 217, 218));
        jButton3.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(27, 137, 136));
        jButton3.setText("refraiche");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(430, 190, 120, 50);

        jButton4.setBackground(new java.awt.Color(194, 217, 218));
        jButton4.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(27, 137, 136));
        jButton4.setText("Modify");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(310, 190, 120, 50);

        jLabel2.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(7, 193, 252));
        jLabel2.setText("type_vmt :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 370, 90, 30);

        txt_tel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_telActionPerformed(evt);
            }
        });
        getContentPane().add(txt_tel);
        txt_tel.setBounds(330, 250, 140, 27);

        jLabel3.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(7, 193, 252));
        jLabel3.setText("id_user :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 250, 60, 20);
        getContentPane().add(id_us);
        id_us.setBounds(90, 250, 140, 30);

        jLabel4.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(7, 193, 252));
        jLabel4.setText("username: ");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 290, 90, 18);
        getContentPane().add(txt_log);
        txt_log.setBounds(90, 290, 140, 30);

        jLabel5.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(7, 193, 252));
        jLabel5.setText("telephone :");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(240, 250, 90, 30);

        txt_typ.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "type_users", "admin", "user" }));
        getContentPane().add(txt_typ);
        txt_typ.setBounds(90, 370, 140, 27);

        txtrech.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtrechActionPerformed(evt);
            }
        });
        getContentPane().add(txtrech);
        txtrech.setBounds(450, 410, 150, 30);

        jLabel7.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(7, 193, 252));
        jLabel7.setText("rechercher by categories :");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(270, 370, 200, 30);

        comrech.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "id", "id_user", "logine", "password", "type", "nom", "prenom", "telephone", "email" }));
        getContentPane().add(comrech);
        comrech.setBounds(460, 370, 120, 27);

        jButton5.setBackground(new java.awt.Color(194, 217, 218));
        jButton5.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jButton5.setForeground(new java.awt.Color(27, 137, 136));
        jButton5.setText("Rechercher");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(300, 410, 130, 33);

        jButton6.setText("log-out");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(570, 460, 130, 20);

        jLabel6.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(7, 193, 252));
        jLabel6.setText("password :");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 320, 90, 40);

        jLabel8.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(7, 193, 252));
        jLabel8.setText("nom:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(20, 410, 60, 18);

        jLabel9.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(7, 193, 252));
        jLabel9.setText("prenom :");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(10, 448, 90, 30);

        jLabel10.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(7, 193, 252));
        jLabel10.setText("e-mail :");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(260, 280, 90, 40);

        txt_pas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_pasActionPerformed(evt);
            }
        });
        getContentPane().add(txt_pas);
        txt_pas.setBounds(90, 330, 140, 27);
        getContentPane().add(txt_nom);
        txt_nom.setBounds(90, 410, 140, 27);
        getContentPane().add(txt_prenom);
        txt_prenom.setBounds(90, 450, 140, 27);

        txt_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_emailActionPerformed(evt);
            }
        });
        getContentPane().add(txt_email);
        txt_email.setBounds(330, 290, 140, 27);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DataBase/images/photo.jpg"))); // NOI18N
        jLabel11.setText("jLabel11");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(0, 0, 780, 490);

        pack();
    }// </editor-fold>//GEN-END:initComponents
//methode permettant la suppression
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
                                                  
        if (id_us.getText().equals("") || txt_log.getText().equals("") || txt_pas.getText().equals("") || txt_nom.getText().equals("")
               || txt_prenom.getText().equals("") || txt_tel.getText().equals("") || txt_email.getText().equals("") || txt_typ.getSelectedItem().equals("Type")) {
            JOptionPane.showConfirmDialog(null, "you must complet the informations", "attention",
                    JOptionPane.OK_OPTION,JOptionPane.INFORMATION_MESSAGE);
        } else {
            String[] colon = {"id_users", "logine", "password", "type", "nom", "prenom", "telephone", "email"};
            String[] inf = {id_us.getText(), txt_log.getText(), txt_pas.getText(), txt_typ.getSelectedItem().toString(), txt_nom.getText(), txt_prenom.getText(), 
               txt_tel.getText(), txt_email.getText(), };
            System.out.println(db.queryInsert("users", colon, inf));
            table();
            actualiser();
        }
        
    }                                        
// method de la suppression
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         String id = String.valueOf(table_user.getValueAt(table_user.getSelectedRow(), 0));
        if (JOptionPane.showConfirmDialog(null, "are you realy sure to delete this users", "attention!!!", JOptionPane.OK_CANCEL_OPTION, JOptionPane.WARNING_MESSAGE) == JOptionPane.OK_OPTION) {
            db.queryDelete("users", "id=" + id);
        } else {
            return;
        }
        table();

    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtrechActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtrechActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtrechActionPerformed
//methode de la modification
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        if (id_us.getText().equals("") || txt_log.getText().equals("") || txt_pas.getText().equals("") || txt_nom.getText().equals("")
               || txt_prenom.getText().equals("") || txt_tel.getText().equals("") || txt_email.getText().equals("") || txt_typ.getSelectedItem().equals("Type")) {
            JOptionPane.showConfirmDialog(null, "please you must enter the informations completly", "warning", JOptionPane.OK_OPTION, JOptionPane.INFORMATION_MESSAGE);
        } else {
           String[] colon = {"id_users", "logine", "password", "type", "nom", "prenom", "telephone", "email"};
            String[] inf = {id_us.getText(), txt_log.getText(), txt_pas.getText(), txt_typ.getSelectedItem().toString(), txt_nom.getText(), txt_prenom.getText(), 
               txt_tel.getText(), txt_email.getText()};
            String id = String.valueOf(table_user.getValueAt(table_user.getSelectedRow(), 0));
            System.out.println(db.queryUpdate("users", colon, inf, "id='" + id + "'"));
            table();
            actualiser();
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        actualiser(); table();
    }//GEN-LAST:event_jButton3ActionPerformed
//methode de la recherche
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        if (txtrech.getText().equals("")) {
            jo = new JOptionPane();
          int option = jo.showConfirmDialog(null, "you must enter anything to searche","Warning",  JOptionPane.OK_CANCEL_OPTION, JOptionPane.INFORMATION_MESSAGE);
        } else {
            if (comrech.getSelectedItem().equals("id_users")) {
                rs = db.querySelectAll("users", "id_users LIKE '%" + txtrech.getText() + "%' ");
                table_user.setModel(new ResultSetTableModel(rs));
            } else if (comrech.getSelectedItem().equals("logine")) {
                rs = db.querySelectAll("users", "logine LIKE '%" + txtrech.getText() + "%' ");
                table_user.setModel(new ResultSetTableModel(rs));
            } else if (comrech.getSelectedItem().equals("password")) {
                rs = db.querySelectAll("users", "password LIKE '%" + txtrech.getText() + "%' ");
                table_user.setModel(new ResultSetTableModel(rs));
            } else if (comrech.getSelectedItem().equals("type")) {
                rs = db.querySelectAll("users", "type LIKE '%" + txtrech.getText() + "%' ");
                table_user.setModel(new ResultSetTableModel(rs));
            }else if (comrech.getSelectedItem().equals("id")) {
                rs = db.querySelectAll("users", "id LIKE '%" + txtrech.getText() + "%' ");
                table_user.setModel(new ResultSetTableModel(rs));
            }else if (comrech.getSelectedItem().equals("nom")) {
                rs = db.querySelectAll("users", "nom LIKE '%" + txtrech.getText() + "%' ");
                table_user.setModel(new ResultSetTableModel(rs));
            }else if (comrech.getSelectedItem().equals("prenom")) {
                rs = db.querySelectAll("users", "prenom LIKE '%" + txtrech.getText() + "%' ");
                table_user.setModel(new ResultSetTableModel(rs));
            }else if (comrech.getSelectedItem().equals("telephone")) {
                rs = db.querySelectAll("users", "telephone LIKE '%" + txtrech.getText() + "%' ");
                table_user.setModel(new ResultSetTableModel(rs));
            }else if (comrech.getSelectedItem().equals("email")) {
                rs = db.querySelectAll("users", "email LIKE '%" + txtrech.getText() + "%' ");
                table_user.setModel(new ResultSetTableModel(rs));
            }
        } 
    }//GEN-LAST:event_jButton5ActionPerformed
//METHOD PERMETANT DE FAIRE APPARAITRE DANS LE FORMULAIRE L ELEMENT CLIQUER A PARTIR DU TABLEAU
    private void table_userMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_userMouseClicked
       id_us.setText(String.valueOf(table_user.getValueAt(table_user.getSelectedRow(),1)));
       txt_log.setText(String.valueOf(table_user.getValueAt(table_user.getSelectedRow(),2)));
       txt_pas.setText(String.valueOf(table_user.getValueAt(table_user.getSelectedRow(),3)));
       txt_typ.setSelectedItem(String.valueOf(table_user.getValueAt(table_user.getSelectedRow(),4)));
       txt_nom.setText(String.valueOf(table_user.getValueAt(table_user.getSelectedRow(),5)));
       txt_prenom.setText(String.valueOf(table_user.getValueAt(table_user.getSelectedRow(),6)));
       txt_tel.setText(String.valueOf(table_user.getValueAt(table_user.getSelectedRow(),7)));
       txt_email.setText(String.valueOf(table_user.getValueAt(table_user.getSelectedRow(),8)));
       
    }//GEN-LAST:event_table_userMouseClicked

    private void jScrollPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane1MouseClicked
      
    }//GEN-LAST:event_jScrollPane1MouseClicked

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        jo1 = new JOptionPane();
        int option = jo1.showConfirmDialog(null, "click to yes to log-out or no to stay on this page", "Caution", JOptionPane.OK_OPTION, JOptionPane.INFORMATION_MESSAGE);
        if(option == JOptionPane.OK_OPTION){
            
            Logine l = new Logine();
            l.setVisible(true);
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void txt_pasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_pasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_pasActionPerformed

    private void txt_telActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_telActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_telActionPerformed

    private void txt_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_emailActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(utilisateur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(utilisateur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(utilisateur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(utilisateur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
           public void run() {
                new utilisateur().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comrech;
    private javax.swing.JTextField id_us;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table_user;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_log;
    private javax.swing.JTextField txt_nom;
    private javax.swing.JTextField txt_pas;
    private javax.swing.JTextField txt_prenom;
    private javax.swing.JTextField txt_tel;
    private javax.swing.JComboBox<String> txt_typ;
    private javax.swing.JTextField txtrech;
    // End of variables declaration//GEN-END:variables
}
